name: CI and Docker Build

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'dev'

permissions:
    contents: read
    packages: write

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
    - name: Run ESLint (JavaScript)
      run: npx eslint "js/**/*.js"
    - name: Run stylelint (CSS)
      run: npx stylelint "css/**/*.css"
    - name: Run HTMLHint (HTML)
      run: npx htmlhint "**/*.html"

  docker:
    needs: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get short SHA
        id: slug
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/nginx/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/yoganovvaindra/wedding:${{ steps.slug.outputs.SHORT_SHA }}
            ghcr.io/yoganovvaindra/wedding:latest
